### PR TITLE
Add milestone of l.d.o launch

### PR DESCRIPTION
**Pull request by BaluErtl**

### CODE REVIEW

**Comment by greggles** [comment]
The 3 things are:
* gitlab
* merge requests
* localize.drupal.org

Seems cool to me.

**Comment by weitzman** [comment]
We have an entry for issue forks. IMO that covers 1. and 2. Please resubmit the entry for localize. Thanks.

**Comment by weitzman** [comment]
Let's skip the hungarian milestone. It's too country specific for this timeline imo.

**Comment by BaluErtl** [comment]
It was inspired by the German local Drupal communityʼs milestone in PR #44 (which is still waiting for merge too).

**Pull request merged**
